# This workflow will launch at 06:00 every day
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repos-file: 'repos.md'
          author-email: eikek-scala-steward@users.noreply.github.comb
          author-name: eikek-scala-steward
